### PR TITLE
Add arm64 build support

### PR DESCRIPTION
**Pull request by giuliobenetti**

### CODE REVIEW

**Comment by giuliobenetti** [comment]
Relaunch Travis, since it hanged on 1 build step(Travis issue).

**Comment by giuliobenetti** [comment]
Travis failed again...

**Comment by mripard** [comment]
I'm not sure what this is supposed to fix or improve. You can already switch between architectures using ARCH=arm or ARCH=arm64, why would we need to do more?

**Comment by giuliobenetti** [comment]
Oh, you're right, ARCH variable is inherited calling make. 
I've made mess through Buildroot recipe.
It was already ready. 
Sorry for wasting time. 
I close this PR.

**Pull request closed without merging**
