### PR TITLE
Add r9p0 kernel driver

### PR DESCRIPTION
**Pull request by rsglobal**
PR tested on v4.20 H3 soc (Orange PI one board)

### CODE REVIEW

**Comment by mripard** [comment]
Hi, thanks for your PR.

The patches themselves look fine, but could you add your Signed-off-by?

Thanks!

**Comment by rsglobal** [comment]
@mripard 
Thanks for review
Signed-off-by lines added
Changes in .travis.yml dropped as them will be generated automatically after next update

**Comment by rsglobal** [comment]
@mripard 
Please merge #62 first, and than I will add support-v5.0 to this PR too.

**Comment by mripard** [comment]
Sorry for the delay, the 5.0 PR have been merged, it would be awesome if you could add the 5.0 fix to that PR as well.

**Comment by rsglobal** [comment]
CI passed with modified travis.yml
https://travis-ci.org/mripard/sunxi-mali/builds/486376534?utm_source=github_status&utm_medium=notification

**Comment by rsglobal** [comment]
.travis.yml dropped again
PR is ready for merging

**Pull request merged**
