### PR TITLE
mail: Fix build in 4.16

### PR DESCRIPTION
**Pull request by giuliobenetti**
This closes Issue #29 

Signed-off-by: Giulio Benetti <giulio.benetti@micronovasrl.com>

### CODE REVIEW

**Comment by giuliobenetti** [comment]
I went out of disk's quota on Travis, this is why it failed.
Relaunching.

**Comment by giuliobenetti** [comment]
Mess with my branches. Now it's ok, sorry for notifications!

**Comment by giuliobenetti** [comment]
Travis is impossibly overloaded tonight.
I retry last time to reopen PR

**Comment by giuliobenetti** [comment]
Retry with Travis

**Comment by giuliobenetti** [comment]
Wrong commit log:
used "mail" instead of "mali"...

**Comment by mripard** [comment]
While you're at it, if the patch only applies to r6p2, it should be in the r6p2 folder.

**Pull request closed without merging**
